#!/bin/sh
# system one time tasks

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

#
# save all environment variables sent to container
export > /etc/envvars

#
# run script once
echo "Run scripts in /etc/run_once"
/bin/run-parts /etc/run_once
# remove scripts in folder
rm -Rf /etc/run_once/*

# run scripts everytime
echo "Run scripts is /etc/run_always"
/bin/run-parts /etc/run_always



touch /etc/runit/stopit
chmod 0 /etc/runit/stopit

